### ISSUE TITLE
4D datasets

### ISSUE THREAD

**Issue by fotaras-github** [ccipd/MRQy#17]
Hi Amir,

Can the tool also deal with 4D datasets (e.g. fMRI)? I find that matplotlib returns an error ('Third dimension must be 3 or 4') when the input is 4D.

Am I missing something here?

Thanks!

**Comment by satishev** [comment]
Looping in @Amir-Reza-Sadri

**Comment by Amir-Reza-Sadri** [comment]
Hello,

It should be working, can you share some of your data with me: ars329@case.edu

Thanks.

**Comment by fotaras-github** [comment]
> Hello,
> 
> It should be working, can you share some of your data with me: [ars329@case.edu](mailto:ars329@case.edu)
> 
> Thanks.

@Amir-Reza-Sadri Done!

**Comment by cammu00** [comment]
Hi Amir,
I got a same error for 4D dataset (fMRI, DTI). How to input my dataset or where could I change in codes?

Thanks!

**Comment by Amir-Reza-Sadri** [comment]
Please use the code QC4d.py instead of QC.py with the same settings for 4D data.
Here are the considerations for this version:
1. Assuming the volumetric 4D data is in the form of x × y × z × w, w is the fourth dimension (let's say the time). Right now, you can run the MRQy for a fixed time volume of the data. Depending on the time sequence of your data, you can specify the desired time at line #147 of the QC4d.py script (default value: time_dim=5).
2. If you want to compare other dimensions of your data in terms of quality metrics, feel free to replace the arguments in line #150.
Some important things:
1. Make sure your data files have different names or id.
2. Make sure your volumetric inputs have the same size.
3. Make sure you have at least 6 input data.
Let me know if this works.
Thanks.

**Comment by fotaras-github** [comment]
> Please use the code QC4d.py instead of QC.py with the same settings for 4D data. Here are the considerations for this version:
> 
> 1. Assuming the volumetric 4D data is in the form of x × y × z × w, w is the fourth dimension (let's say the time). Right now, you can run the MRQy for a fixed time volume of the data. Depending on the time sequence of your data, you can specify the desired time at line #147 of the QC4d.py script (default value: time_dim=5).
> 2. If you want to compare other dimensions of your data in terms of quality metrics, feel free to replace the arguments in line #150.
>    Some important things:
> 3. Make sure your data files have different names or id.
> 4. Make sure your volumetric inputs have the same size.
> 5. Make sure you have at least 6 input data.
>    Let me know if this works.
>    Thanks.

Thank you for the update Amir. 

With the default `time_dim=5,` QC4d.py works on datasets with the following dimensions: [64x64x36x200]. But what is `time_dim` exactly? Time, in seconds/milliseconds, required for each volume? That's the part unclear to me.

**Comment by Amir-Reza-Sadri** [comment]
It is the desired time that you want to run the QC over. This way, the tool focuses/compares all scans in a single time-origin.
