### ISSUE TITLE
Please  help cann't read data 

### ISSUE THREAD

**Issue by a402083555** [ccipd/MRQy#28]
I used pipenv to run the MRQY。
input：(a4020-WYmTOfA1) (base) C:\Users\a4020\Documents\GitHub\MRQy\src\mrqy>python QC.py MR_RAW 'C:\Users\a4020\Desktop\mrqy learning\MR-nii'

output：MRQy is starting....
The number of patients is 0
The input folder is empty or includes unsupported files format!
Skipped the t-SNE and UMAP computation because of insufficient data. The UMAP and t-SNE process need at least 6 input data.
Traceback (most recent call last):
  File "QC.py", line 376, in <module>
    df = tsv_to_dataframe(address)
  File "QC.py", line 205, in tsv_to_dataframe
    return pd.read_csv(tsvfileaddress, sep='\t', skiprows=2, header=0)
  File "C:\Users\a4020\.virtualenvs\a4020-WYmTOfA1\lib\site-packages\pandas\io\parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\a4020\.virtualenvs\a4020-WYmTOfA1\lib\site-packages\pandas\io\parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\a4020\.virtualenvs\a4020-WYmTOfA1\lib\site-packages\pandas\io\parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "C:\Users\a4020\.virtualenvs\a4020-WYmTOfA1\lib\site-packages\pandas\io\parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\a4020\.virtualenvs\a4020-WYmTOfA1\lib\site-packages\pandas\io\parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by a402083555** [comment]
My python version is 3.7.

pipenv package:
colorama           0.4.6
cycler             0.11.0
fonttools          4.38.0
imageio            2.31.1
importlib-metadata 6.7.0
joblib             1.3.2
kiwisolver         1.4.4
llvmlite           0.39.1
matplotlib         3.5.3
MedPy              0.4.0
mrqy               0.1
networkx           2.6.3
numba              0.56.4
numpy              1.21.6
packaging          23.1
pandas             1.1.5
Pillow             9.5.0
pip                23.2.1
pydicom            2.4.2
pynndescent        0.5.10
pyparsing          3.1.1
python-dateutil    2.8.2
pytz               2023.3
PyWavelets         1.3.0
scikit-image       0.19.3
scikit-learn       1.0.2
scipy              1.7.3
setuptools         68.0.0
SimpleITK          2.2.1
six                1.16.0
threadpoolctl      3.1.0
tifffile           2021.11.2
tqdm               4.66.1
typing_extensions  4.7.1
umap-learn         0.5.3
wheel              0.41.1
zipp               3.15.0

**Comment by satishev** [comment]
@Amir-Reza-Sadri take a look

**Comment by Amir-Reza-Sadri** [comment]
Thank you for reaching out.

Based on the tool's message: "The input folder is empty or includes unsupported file formats!", please ensure the following:

1. Verify that you're pointing to the correct folder location.
2. Ensure that the files within the folder are of supported formats.

If you're still facing issues, please share a sample of your input data or the list of file types you're trying to process. I'd be happy to take a closer look and assist you further.

**Comment by drkitty28** [comment]
I'm having a similar problem on an Ubuntu 20.04 system. I don't get an error about "unsupported files", but MRQy doesn't seem to read the input directory
![Screenshot from 2023-11-15 12-48-16](https://github.com/ccipd/MRQy/assets/26172078/6dfacad3-5006-4865-a32c-2d96cf407d3b).  If I use as the output folder "Test" which is prepopulated, MRQy runs, but still doesn't read the input directory 
![Screenshot from 2023-11-15 12-49-04](https://github.com/ccipd/MRQy/assets/26172078/a190be1f-74fe-4e17-ab32-47181e540c35)
I've tried various locations for the input directory, both inside and outside the MRQy-New-Version directory, with no luck. Is there a specific location where the input should be?

**Comment by drkitty28** [comment]
I installed the MRQy-2022.04 and ran it.  Now it finds the input directory and creates the output folder in the UserInterface/Data directory, but it returns the error:  ValueError: Third dimension must be 3 or 4 - So, don't know what this means
![Screenshot from 2023-11-15 13-43-27](https://github.com/ccipd/MRQy/assets/26172078/8806683f-036b-4c05-a2ee-70a02167139a)

**Comment by drkitty28** [comment]
Any ideas about this?

**Comment by Amir-Reza-Sadri** [comment]
Thank you for reaching out and providing the details of the error you encountered. Based on the error message "ValueError: Third dimension must be 3 or 4", it appears that the issue is related to the dimensionality of the image data being processed.

Our tool is designed to work with medical imaging standard formats, which typically do not include color channels as seen in standard RGB or RGBA images. It seems the data you are attempting to process may contain color information, which is not supported by our tool.

To resolve this, please ensure that the images are in a supported medical imaging format (like DICOM, NIfTI, or similar grayscale formats) before passing them to the tool. If you are working with non-medical standard color images, you might need to convert them to grayscale or extract the relevant channels to fit the expected input format for the tool.

If you're indeed working with medical images and still encountering this error, please double-check that the images have not been inadvertently converted to a color format during preprocessing or loading. The tool expects the input data to be in grayscale with a shape that corresponds to (height, width) for 2D images or (slices, height, width) for 3D volumes.

Let me know if you need further assistance or if there are any additional details you can provide.

**Comment by drkitty28** [comment]
These are standard nii images from a Siemens 3T Prisma.  No color, standard dicom to nifti conversion. They are BOLD images 4D (slices, height, width, time). Can MRQy could handle 4D?

**Comment by Amir-Reza-Sadri** [comment]
see https://github.com/ccipd/MRQy/issues/17

**Comment by mohsenhariri** [comment]
Closes #28 in favor of #17
